#!/usr/bin/env python3
"""Build advisor-facing tables and figures for the retriever-policy report.

The script consumes only the BM25/Dense analysis generated by
``analyze_beir_retriever_policy.py`` and local BEIR manifests/query/qrels files.
It does not execute retrieval, reranking, model inference, or generation.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch


ORDER = [
    "arguana",
    "fiqa",
    "hotpotqa",
    "nfcorpus",
    "nq",
    "webis-touche2020",
    "cqadupstack",
]
DISPLAY = {
    "arguana": "ArguAna",
    "fiqa": "FiQA-2018",
    "hotpotqa": "HotpotQA",
    "nfcorpus": "NFCorpus",
    "nq": "NQ",
    "webis-touche2020": "Touché-2020",
    "cqadupstack": "CQADupStack",
    "selected7_equal": "Selected-7 macro",
}


def args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--analysis-dir",
        type=Path,
        default=Path("docs/assets/history_aware_retriever_policy/analysis"),
    )
    parser.add_argument("--beir-root", type=Path, default=Path("data/beir"))
    parser.add_argument(
        "--figure-dir",
        type=Path,
        default=Path("docs/assets/history_aware_retriever_policy/figures"),
    )
    return parser.parse_args()


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def f(row: dict[str, str], key: str) -> float:
    return float(row[key])


def qrel_query_ids(path: Path) -> tuple[set[str], dict[str, int]]:
    positive: dict[str, int] = defaultdict(int)
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            if float(row["score"]) > 0:
                positive[str(row["query-id"])] += 1
    return set(positive), positive


def unit_profile(unit_root: Path) -> dict[str, float]:
    manifest = json.loads((unit_root / "manifest.json").read_text(encoding="utf-8"))
    query_ids, positive = qrel_query_ids(unit_root / "qrels" / "test.tsv")
    lengths: list[int] = []
    chars: list[int] = []
    question_marks = 0
    with (unit_root / "queries" / "queries.jsonl").open("r", encoding="utf-8") as handle:
        for line in handle:
            row = json.loads(line)
            if str(row["_id"]) not in query_ids:
                continue
            text = str(row["text"]).strip()
            lengths.append(len(text.split()))
            chars.append(len(text))
            question_marks += int("?" in text)
    if len(lengths) != len(query_ids):
        raise RuntimeError(f"query/qrels mismatch in {unit_root}: {len(lengths)} != {len(query_ids)}")
    relevant_counts = [positive[qid] for qid in query_ids]
    return {
        "corpus_docs": float(manifest["counts"]["retrievable_corpus_rows"]),
        "test_queries": float(len(query_ids)),
        "avg_query_terms": statistics.fmean(lengths),
        "median_query_terms": statistics.median(lengths),
        "avg_query_chars": statistics.fmean(chars),
        "question_mark_fraction": question_marks / len(lengths),
        "avg_relevant_docs": statistics.fmean(relevant_counts),
        "multi_relevant_fraction": sum(value > 1 for value in relevant_counts) / len(relevant_counts),
    }


def build_dataset_profile(beir_root: Path) -> list[dict]:
    rows: list[dict] = []
    for family in ORDER:
        root = beir_root / family
        if family == "cqadupstack":
            collection = json.loads((root / "manifest.json").read_text(encoding="utf-8"))
            profiles = [unit_profile(root / item["path"]) for item in collection["units"].values()]
            profile = {
                "corpus_docs": sum(item["corpus_docs"] for item in profiles),
                "test_queries": sum(item["test_queries"] for item in profiles),
                **{
                    key: statistics.fmean(item[key] for item in profiles)
                    for key in (
                        "avg_query_terms",
                        "median_query_terms",
                        "avg_query_chars",
                        "question_mark_fraction",
                        "avg_relevant_docs",
                        "multi_relevant_fraction",
                    )
                },
            }
            aggregation = "12-forum equal for descriptive means"
            units = 12
        else:
            profile = unit_profile(root)
            aggregation = "test-query macro"
            units = 1
        rows.append({
            "family": family,
            "family_display": DISPLAY[family],
            "units": units,
            "aggregation": aggregation,
            "corpus_docs": int(profile["corpus_docs"]),
            "test_queries": int(profile["test_queries"]),
            "avg_query_terms_whitespace": profile["avg_query_terms"],
            "median_query_terms_whitespace": profile["median_query_terms"],
            "avg_query_chars": profile["avg_query_chars"],
            "question_mark_fraction": profile["question_mark_fraction"],
            "avg_positive_qrels_per_query": profile["avg_relevant_docs"],
            "multi_positive_qrels_fraction": profile["multi_relevant_fraction"],
        })
    return rows


def build_evidence_table(analysis: Path) -> list[dict]:
    base = {row["family"]: row for row in read_csv(analysis / "bm25_dense_k10_summary.csv")}
    pools = {row["family"]: row for row in read_csv(analysis / "candidate_pool_complementarity.csv")}
    best = {
        row["family"]: row
        for row in read_csv(analysis / "rrf_best_alpha_test_oracle.csv")
        if row["protocol"] == "equal50" and row["family"] != "selected7_equal"
    }
    oracle = {
        row["family"]: row
        for row in read_csv(analysis / "query_policy_oracle_summary.csv")
        if row["protocol"] == "equal50" and row["family"] != "selected7_equal"
    }
    rows: list[dict] = []
    for family in ORDER:
        b, p, h, o = base[family], pools[family], best[family], oracle[family]
        rows.append({
            "family": family,
            "family_display": DISPLAY[family],
            "bm25_ndcg_at_10": f(b, "bm25_ndcg_at_10"),
            "dense_ndcg_at_10": f(b, "dense_ndcg_at_10"),
            "best_fixed_single": b["best_fixed_single"],
            "dense_query_win_fraction": f(b, "dense_query_win_fraction"),
            "bm25_query_win_fraction": f(b, "bm25_query_win_fraction"),
            "query_tie_fraction": f(b, "query_tie_fraction"),
            "top50_candidate_jaccard": f(p, "candidate_jaccard"),
            "bm25_only_relevant_fraction": f(p, "bm25_only_relevant_fraction"),
            "dense_only_relevant_fraction": f(p, "dense_only_relevant_fraction"),
            "union_recall_headroom": f(p, "union_headroom_over_better_fixed_pool"),
            "fixed_rrf_alpha_0_5_ndcg_at_10": f(h, "alpha_0_5_ndcg_at_10"),
            "test_oracle_fixed_alpha_bm25": f(h, "best_alpha_min"),
            "test_oracle_fixed_rrf_ndcg_at_10": f(h, "best_test_oracle_ndcg_at_10"),
            "query_oracle_best_single_ndcg_at_10": f(o, "query_oracle_best_single_ndcg_at_10"),
            "query_oracle_single_or_hybrid_ndcg_at_10": f(o, "query_oracle_single_or_hybrid_ndcg_at_10"),
            "hybrid_strict_gain_query_fraction": f(o, "hybrid_strict_gain_query_fraction"),
        })
    return rows


def build_hotpot_complete_support(analysis: Path) -> list[dict]:
    rows = [
        row for row in read_csv(analysis / "query_level_bm25_dense.csv")
        if row["family"] == "hotpotqa"
    ]
    return [{
        "family": "hotpotqa",
        "num_queries": len(rows),
        "bm25_top50_complete_two_of_two_fraction": statistics.fmean(
            math.isclose(float(row["bm25_recall_at_50"]), 1.0) for row in rows
        ),
        "dense_top50_complete_two_of_two_fraction": statistics.fmean(
            math.isclose(float(row["dense_recall_at_50"]), 1.0) for row in rows
        ),
        "union_up_to100_complete_two_of_two_fraction": statistics.fmean(
            math.isclose(float(row["union_recall_at_up_to_100"]), 1.0) for row in rows
        ),
        "warning": "Top-50 plus Top-50 union is a coverage ceiling, not a same-budget hybrid",
    }]


def build_strict_hybrid_alpha_distribution(analysis: Path) -> list[dict]:
    rows = [
        row for row in read_csv(analysis / "query_policy_oracle.csv")
        if row["protocol"] == "equal50"
    ]
    oracle_summary = {
        row["family"]: row
        for row in read_csv(analysis / "query_policy_oracle_summary.csv")
        if row["protocol"] == "equal50"
    }
    output: list[dict] = []
    for family in ORDER:
        family_rows = [row for row in rows if row["family"] == family]
        strict = [row for row in family_rows if row["hybrid_strictly_beats_both_singles"] == "1"]
        midpoints = [
            (float(row["best_alpha_min"]) + float(row["best_alpha_max"])) / 2
            for row in strict
        ]
        output.append({
            "family": family,
            "aggregation_for_strict_fraction": "forum_equal" if family == "cqadupstack" else "query_macro",
            "num_queries": len(family_rows),
            "strict_hybrid_queries_raw": len(strict),
            "strict_hybrid_fraction": float(oracle_summary[family]["hybrid_strict_gain_query_fraction"]),
            "alpha_distribution_aggregation": "query_weighted diagnostic",
            "optimal_alpha_interval_midpoint_median": statistics.median(midpoints),
            "dense_heavy_alpha_le_0_25_fraction": statistics.fmean(value <= 0.25 for value in midpoints),
            "balanced_alpha_between_0_25_and_0_75_fraction": statistics.fmean(0.25 < value < 0.75 for value in midpoints),
            "bm25_heavy_alpha_ge_0_75_fraction": statistics.fmean(value >= 0.75 for value in midpoints),
        })
    output.append({
        "family": "selected7_equal",
        "aggregation_for_strict_fraction": "family_equal",
        "num_queries": sum(int(row["num_queries"]) for row in output),
        "strict_hybrid_queries_raw": sum(int(row["strict_hybrid_queries_raw"]) for row in output),
        "strict_hybrid_fraction": float(oracle_summary["selected7_equal"]["hybrid_strict_gain_query_fraction"]),
        "alpha_distribution_aggregation": "family-equal over query-weighted family diagnostics",
        "optimal_alpha_interval_midpoint_median": statistics.median(
            float(row["optimal_alpha_interval_midpoint_median"]) for row in output
        ),
        "dense_heavy_alpha_le_0_25_fraction": statistics.fmean(
            float(row["dense_heavy_alpha_le_0_25_fraction"]) for row in output
        ),
        "balanced_alpha_between_0_25_and_0_75_fraction": statistics.fmean(
            float(row["balanced_alpha_between_0_25_and_0_75_fraction"]) for row in output
        ),
        "bm25_heavy_alpha_ge_0_75_fraction": statistics.fmean(
            float(row["bm25_heavy_alpha_ge_0_75_fraction"]) for row in output
        ),
    })
    return output


def configure_plotting() -> None:
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Microsoft YaHei", "Noto Sans CJK SC", "DejaVu Sans"],
        "axes.unicode_minus": False,
        "figure.facecolor": "white",
        "axes.facecolor": "#fbfcfe",
        "axes.edgecolor": "#ccd3dd",
        "axes.titleweight": "bold",
        "font.size": 10,
    })


def plot_landscape(evidence: list[dict], analysis: Path, path: Path) -> None:
    names = [row["family_display"] for row in evidence]
    y = np.arange(len(names))
    fig, axes = plt.subplots(2, 2, figsize=(16, 11), constrained_layout=True)

    ax = axes[0, 0]
    width = 0.36
    ax.barh(y - width / 2, [row["bm25_ndcg_at_10"] for row in evidence], width, label="BM25", color="#d98c3f")
    ax.barh(y + width / 2, [row["dense_ndcg_at_10"] for row in evidence], width, label="Dense", color="#3f73b5")
    ax.set_yticks(y, names)
    ax.invert_yaxis()
    ax.set_xlabel("nDCG@10")
    ax.set_title("A. Family-level fixed single retrievers")
    ax.legend(loc="lower right")
    ax.grid(axis="x", alpha=0.22)

    ax = axes[0, 1]
    left = np.zeros(len(evidence))
    for key, label, color in (
        ("bm25_query_win_fraction", "BM25 wins", "#d98c3f"),
        ("query_tie_fraction", "Tie", "#c8cdd5"),
        ("dense_query_win_fraction", "Dense wins", "#3f73b5"),
    ):
        values = np.array([row[key] for row in evidence])
        ax.barh(y, values, left=left, label=label, color=color)
        left += values
    ax.set_yticks(y, names)
    ax.invert_yaxis()
    ax.set_xlim(0, 1)
    ax.set_xlabel("Fraction of queries")
    ax.set_title("B. Query-level BM25 vs Dense outcomes")
    ax.legend(ncols=3, loc="lower center", fontsize=9)

    pools = {row["family"]: row for row in read_csv(analysis / "candidate_pool_complementarity.csv")}
    ax = axes[1, 0]
    left = np.zeros(len(evidence))
    for key, label, color in (
        ("bm25_only_relevant_fraction", "BM25-only gold", "#d98c3f"),
        ("shared_relevant_fraction", "Shared gold", "#6e8f67"),
        ("dense_only_relevant_fraction", "Dense-only gold", "#3f73b5"),
        ("neither_relevant_fraction", "Neither Top-50", "#d7d9de"),
    ):
        values = np.array([float(pools[row["family"]][key]) for row in evidence])
        ax.barh(y, values, left=left, label=label, color=color)
        left += values
    ax.set_yticks(y, names)
    ax.invert_yaxis()
    ax.set_xlim(0, 1)
    ax.set_xlabel("Fraction of positive qrels")
    ax.set_title("C. Relevant-document source decomposition (Top-50 pools)")
    ax.legend(ncols=2, loc="lower center", fontsize=8)

    oracle = {
        row["family"]: row
        for row in read_csv(analysis / "query_policy_oracle_summary.csv")
        if row["protocol"] == "equal50" and row["family"] != "selected7_equal"
    }
    ax = axes[1, 1]
    fixed = [max(row["bm25_ndcg_at_10"], row["dense_ndcg_at_10"]) for row in evidence]
    single = [float(oracle[row["family"]]["query_oracle_best_single_ndcg_at_10"]) for row in evidence]
    all_actions = [float(oracle[row["family"]]["query_oracle_single_or_hybrid_ndcg_at_10"]) for row in evidence]
    for index in range(len(evidence)):
        ax.plot([fixed[index], single[index], all_actions[index]], [index] * 3, color="#b8bec8", linewidth=2, zorder=1)
    ax.scatter(fixed, y, marker="o", s=55, color="#27364a", label="Best fixed single", zorder=2)
    ax.scatter(single, y, marker="s", s=55, color="#4c9f70", label="Per-query single oracle", zorder=2)
    ax.scatter(all_actions, y, marker="D", s=55, color="#b34b65", label="Per-query single/hybrid oracle", zorder=2)
    ax.set_yticks(y, names)
    ax.invert_yaxis()
    ax.set_xlabel("nDCG@10")
    ax.set_title("D. Deployable baseline → qrels-based oracle headroom")
    ax.legend(loc="lower right", fontsize=8)
    ax.grid(axis="x", alpha=0.22)

    fig.suptitle("Selected-7: aggregate winners hide query-level retriever complementarity", fontsize=17, fontweight="bold")
    fig.savefig(path, dpi=190, bbox_inches="tight")
    plt.close(fig)


def plot_alpha_curves(analysis: Path, path: Path) -> None:
    rows = [row for row in read_csv(analysis / "rrf_alpha_curves.csv") if row["protocol"] == "equal50"]
    best_rows = {
        row["family"]: row
        for row in read_csv(analysis / "rrf_best_alpha_test_oracle.csv")
        if row["protocol"] == "equal50"
    }
    families = ORDER + ["selected7_equal"]
    fig, axes = plt.subplots(2, 4, figsize=(16, 8.5), sharex=True, constrained_layout=True)
    for ax, family in zip(axes.flat, families):
        values = sorted((row for row in rows if row["family"] == family), key=lambda row: float(row["alpha_bm25"]))
        x = [float(row["alpha_bm25"]) for row in values]
        y = [float(row["ndcg_at_10"]) for row in values]
        best = best_rows[family]
        best_alpha = float(best["best_alpha_min"])
        best_value = float(best["best_test_oracle_ndcg_at_10"])
        ax.plot(x, y, color="#4169a1", linewidth=2.2)
        ax.scatter([0, 1], [y[0], y[-1]], color=["#3f73b5", "#d98c3f"], s=35, zorder=3)
        ax.scatter([best_alpha], [best_value], color="#b34b65", marker="D", s=45, zorder=4)
        ax.axvline(0.5, color="#8b9099", linestyle="--", linewidth=1)
        ax.set_title(f"{DISPLAY[family]}\nbest test-oracle α={best_alpha:.2f}")
        ax.set_xlim(0, 1)
        ax.grid(alpha=0.2)
    for ax in axes[1, :]:
        ax.set_xlabel("BM25 weight α  (0=Dense, 1=BM25)")
    for ax in axes[:, 0]:
        ax.set_ylabel("nDCG@10")
    fig.suptitle("Same-budget weighted RRF is strongly domain-dependent (BM25@25 + Dense@25)", fontsize=16, fontweight="bold")
    fig.savefig(path, dpi=190, bbox_inches="tight")
    plt.close(fig)


def draw_box(ax, xy: tuple[float, float], width: float, height: float, text: str, color: str) -> None:
    box = FancyBboxPatch(
        xy, width, height, boxstyle="round,pad=0.018,rounding_size=0.025",
        facecolor=color, edgecolor="#334155", linewidth=1.4,
    )
    ax.add_patch(box)
    ax.text(xy[0] + width / 2, xy[1] + height / 2, text, ha="center", va="center", fontsize=10.5)


def arrow(ax, start: tuple[float, float], end: tuple[float, float], color: str = "#475569") -> None:
    ax.add_patch(FancyArrowPatch(start, end, arrowstyle="-|>", mutation_scale=14, linewidth=1.5, color=color))


def plot_study_design(path: Path) -> None:
    fig, ax = plt.subplots(figsize=(17, 7.2))
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    ax.axis("off")
    stages = [
        (0.03, "1  BEIR Selected-7\nCross-sectional evidence\nretriever heterogeneity\n+ oracle headroom\n(no temporal claim)", "#e8f0fb"),
        (0.275, "2  Session benchmark\nQReCC / TopiOCQA / TREC\ntrue session_id + turn order\ncomplete action grid", "#e8f7ee"),
        (0.52, "3  RQ1 → RQ2\nmeasure action persistence\nquery-only vs history ablations\npredict gate + α", "#fff3dc"),
        (0.765, "4  RQ3\nretrieval + RAG + cost\nmatched action space\nPareto / constrained utility", "#f8e8ef"),
    ]
    for x, label, color in stages:
        draw_box(ax, (x, 0.56), 0.205, 0.31, label, color)
    for x in (0.235, 0.48, 0.725):
        arrow(ax, (x, 0.715), (x + 0.035, 0.715))

    draw_box(ax, (0.075, 0.16), 0.16, 0.18, "Current query $q_t$\n+ observable $H_{<t}$", "#eef2ff")
    draw_box(ax, (0.31, 0.16), 0.16, 0.18, "Pre-retrieval policy\nSingle or Hybrid?\nBM25 / Dense / α", "#f4f1ff")
    draw_box(ax, (0.545, 0.16), 0.16, 0.18, "Execute selected path(s)\n1 call for single\n2 calls for hybrid", "#f1f5f9")
    draw_box(ax, (0.78, 0.16), 0.16, 0.18, "Observe allowed feedback\nquality proxy + latency\nappend to next history", "#ecfdf5")
    for x in (0.235, 0.47, 0.705):
        arrow(ax, (x, 0.25), (x + 0.07, 0.25))
    ax.text(
        0.5, 0.055,
        "Leakage rule: current-turn qrels and unexecuted retriever outcomes are oracle-only; they are never policy inputs at inference.",
        ha="center", va="center", color="#9f1239", fontsize=11, fontweight="bold",
    )
    ax.set_title("Evidence chain and deployable history-aware retrieval policy", fontsize=18, fontweight="bold", pad=15)
    fig.savefig(path, dpi=190, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    options = args()
    options.figure_dir.mkdir(parents=True, exist_ok=True)
    configure_plotting()

    profile = build_dataset_profile(options.beir_root)
    evidence = build_evidence_table(options.analysis_dir)
    hotpot_support = build_hotpot_complete_support(options.analysis_dir)
    strict_alpha = build_strict_hybrid_alpha_distribution(options.analysis_dir)
    write_csv(options.analysis_dir / "selected7_dataset_profile.csv", profile)
    write_csv(options.analysis_dir / "family_policy_evidence.csv", evidence)
    write_csv(options.analysis_dir / "hotpot_complete_support.csv", hotpot_support)
    write_csv(options.analysis_dir / "strict_hybrid_optimal_alpha_distribution.csv", strict_alpha)

    plot_landscape(evidence, options.analysis_dir, options.figure_dir / "retriever_complementarity_landscape.png")
    plot_alpha_curves(options.analysis_dir, options.figure_dir / "weighted_rrf_alpha_curves_equal50.png")
    plot_study_design(options.figure_dir / "rq1_rq3_evidence_and_policy_design.png")

    macro_best = next(
        row for row in read_csv(options.analysis_dir / "rrf_best_alpha_test_oracle.csv")
        if row["protocol"] == "equal50" and row["family"] == "selected7_equal"
    )
    macro_oracle = next(
        row for row in read_csv(options.analysis_dir / "query_policy_oracle_summary.csv")
        if row["protocol"] == "equal50" and row["family"] == "selected7_equal"
    )
    payload = {
        "status": "passed",
        "retrieval_or_model_inference_executed": False,
        "dataset_profile_family_count": len(profile),
        "evidence_family_count": len(evidence),
        "figures": sorted(path.name for path in options.figure_dir.glob("*.png")),
        "selected7_equal50": {
            "best_fixed_single_ndcg_at_10": float(macro_best["best_fixed_single_ndcg_at_10"]),
            "fixed_alpha_0_5_ndcg_at_10": float(macro_best["alpha_0_5_ndcg_at_10"]),
            "test_oracle_best_fixed_alpha_bm25": float(macro_best["best_alpha_min"]),
            "test_oracle_best_fixed_hybrid_ndcg_at_10": float(macro_best["best_test_oracle_ndcg_at_10"]),
            "query_oracle_best_single_ndcg_at_10": float(macro_oracle["query_oracle_best_single_ndcg_at_10"]),
            "query_oracle_single_or_hybrid_ndcg_at_10": float(macro_oracle["query_oracle_single_or_hybrid_ndcg_at_10"]),
            "hybrid_strict_gain_query_fraction": float(macro_oracle["hybrid_strict_gain_query_fraction"]),
        },
    }
    (options.analysis_dir / "report_build_validation.json").write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(payload, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
